### ISSUE TITLE
where can i download files for label_mngr?

### ISSUE THREAD

**Issue by lfwin** [AIS-Bonn/lidar_mars_registration#4]
Hi,

I try to run your code with 'test2.bag' dataset right now, but have a problem when reaching this line of code:
`m_label_manager = std::make_shared<easy_pbr::LabelMngr>(mngr_config);`
this line of code need following file,
`    labels_file: "./data/mapillary_labels.txt"
    color_scheme_file: "./data/mapillary_color_scheme.txt"
    frequency_file: "./data/mapillary_frequency.txt"`
where can i download these files? thanks for your open source code.

**Comment by JanQuenzel** [comment]
Hi Ifwin,
those files are remnants from visualizing semantically annotated data.
I added them into the repo, but they are not used unless `has_semantics_v<MarsMapPointCloud>` evaluates to true (false by default).
Best, Jan

**Comment by lfwin** [comment]
This problem is solved, thx
