### ISSUE TITLE
How can I set map of DenseVoxelGrid? Right now, the type of the map is set to PermutohedralLattice by default.

### ISSUE THREAD

**Issue by lfwin** [AIS-Bonn/lidar_mars_registration#6]
If I change code in file MarsFwdDec.h as following, 
`typedef MarsMapBase<SparseVoxelGrid> SparseMarsMap;
typedef MarsMapBase<BlockSparseVoxelGrid> BlockSparseMarsMap;
typedef MarsMapBase<DenseVoxelGrid> DenseMarsMap;
typedef MarsMapBase<Lattice> LatticeMarsMap;
typedef DenseMarsMap MarsMap;
//typedef BlockSparseMarsMap MarsMap;
//typedef SparseMarsMap MarsMap;
//typedef LatticeMarsMap MarsMap;
`
the linking error occurs,
[ 98%] Building CXX object CMakeFiles/run_lidar_mars_registration.dir/src/main.cxx.o
    [100%] Building CXX object CMakeFiles/lidar_mars_registration.dir/src/PyBridge.cxx.o
    [100%] Linking CXX executable lidar_mars_registration_node
    /usr/bin/ld: ../../liblidar_mars_registration_libs.so: undefined reference to `MarsMapBase<DenseVoxelGrid>::getCellSize(int const&) const'
    /usr/bin/ld: ../../liblidar_mars_registration_libs.so: undefined reference to `MarsMapBase<DenseVoxelGrid>::transform(Sophus::SE3<double, 0> const&)'
    /usr/bin/ld: ../../liblidar_mars_registration_libs.so: undefined reference to `MarsMapBase<DenseVoxelGrid>::getCellsOnLevel(int const&, std::vector<SurfelInfo, std::allocator<SurfelInfo> >&, bool const&) const'

**Comment by JanQuenzel** [comment]
You have to also uncomment the explicite template instantiation:
https://github.com/AIS-Bonn/lidar_mars_registration/blob/main/src/MarsMap.cxx#L424
